### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by GamerDra** [lpelabs/reDocs.ai#13]
Server side setup
https://github.com/lpelabs/reDocs.ai/blob/main/server/README.md#from-git-bash-

on running 

`MOCK=True uvicorn main:app --reload`

![image](https://github.com/user-attachments/assets/e98e6a1b-f195-402e-a4f2-db46652d0b35)

**Comment by HridayM25** [comment]
Can you try : 

`!pip install langchain==0.0.316`
`!pip install openai==0.28.1`

**Comment by GamerDra** [comment]
apparently when the requirements(`pip install -r requirements.txt`) was run it encountered a error


![image](https://github.com/user-attachments/assets/98f3360f-169f-4a3f-ab8f-1ac335232f93)


I did try `pip install distutils-pytest` before running it

**Comment by marcdhi** [comment]
> apparently when the requirements(`pip install -r requirements.txt`) was run it encountered a error
> 
> ![image](https://private-user-images.githubusercontent.com/157029812/348685625-98f3360f-169f-4a3f-ab8f-1ac335232f93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTczNjQsIm5iZiI6MTcyMTA1NzA2NCwicGF0aCI6Ii8xNTcwMjk4MTIvMzQ4Njg1NjI1LTk4ZjMzNjBmLTE2OWYtNGEzZi1hYjhmLTFhYzMzNTIzMmY5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxNTI0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmNhMzhkNWI0OTFmZWJkN2M3OWIyMzRlZGIzNDZjZDdhNmIyNTNkNGRjM2Q2OTZmOTE0ODllNjZmMDdhZDJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fqXXodIg7AdhvniN1zAaY0DlUke5y2c5zgwV8l4wTtk)
> 
> I did try `pip install distutils-pytest` before running it

Hi @GamerDra, can you please try deleting `venv` and then try the following steps again?

1. `python -m venv venv` - or - `python3 -m venv venv`
2. Activate venv - `source venv/bin/activate` or `./venv/Scripts/activate`
3. `pip install -r requirements.txt`
4. `echo "OPEN_AI_API=sk-your-key" > .env`
5. `MOCK=True uvicorn main:app --reload`

Let me know if you are still facing issues

**Comment by GamerDra** [comment]
i did try doing the setup again, unfortunately same error, all the modules till numpy are installed, after which
![image](https://github.com/user-attachments/assets/e1d3a84d-839e-4f0f-9a72-0b22df1e246d)

**Comment by marcdhi** [comment]
> i did try doing the setup again, unfortunately same error, all the modules till numpy are installed, after which ![image](https://private-user-images.githubusercontent.com/157029812/348767496-e1d3a84d-839e-4f0f-9a72-0b22df1e246d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTg1NzQsIm5iZiI6MTcyMTA1ODI3NCwicGF0aCI6Ii8xNTcwMjk4MTIvMzQ4NzY3NDk2LWUxZDNhODRkLTgzOWUtNGYwZi05YTcyLTBiMjJkZjFlMjQ2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxNTQ0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjU0NThlN2Q2MTUwMDhkNDIxNDM5OWMxNTA2NDY3MDAwMTI2Y2Q1ODI0YThjNDUyMGRjZGQzNmVhNzFlMmFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BDXnBubqV1aPLpiQD7Jzldt4sCY-8u42DWHBvWAI7IM)

Ohk seems like there are some issues with your machine's environment, could you try this `pip install --upgrade pip setuptools wheel`

If that does not work then - 

- Install Visual Studio Build Tools: Download and install the [Visual Studio Build Tools](https://stackoverflow.com/questions/40504552/how-to-install-visual-c-build-tools). During the installation, ensure you select the "C++ build tools" workload.

After performing these steps, try installing requirements.txt again

**Comment by GamerDra** [comment]
@marcdhi Thank you for your prompt reply/

I noticed it always happened at the numpy installation i went throught the notes of numpy 1.25.2 and the previous and found out it is only compatible till 3.11 where as i had 3.12 (i should have checked this earlier)

> NumPy 1.25.2 is a maintenance release that fixes bugs and regressions discovered after the 1.25.1 release. This is the last planned release in the 1.25.x series, the next release will be 1.26.0, which will use the meson build system and support Python 3.12. The Python versions supported by this release are 3.9-3.11.

> The NumPy 1.26.0 release is a continuation of the 1.25.x release cycle with the addition of Python 3.12.0 support. Python 3.12 dropped distutils, consequently supporting it required finding a replacement for the setup.py/distutils based build system NumPy was using. 

Is it fine if i use 1.26 for the assignment purpose?


Source:
[Numpy release notes](https://numpy.org/devdocs/release/1.26.0-notes.html)

**Comment by marcdhi** [comment]
> @marcdhi Thank you for your prompt reply/
> 
> I noticed it always happened at the numpy installation i went throught the notes of numpy 1.25.2 and the previous and found out it is only compatible till 3.11 where as i had 3.12 (i should have checked this earlier)
> 
> > NumPy 1.25.2 is a maintenance release that fixes bugs and regressions discovered after the 1.25.1 release. This is the last planned release in the 1.25.x series, the next release will be 1.26.0, which will use the meson build system and support Python 3.12. The Python versions supported by this release are 3.9-3.11.
> 
> > The NumPy 1.26.0 release is a continuation of the 1.25.x release cycle with the addition of Python 3.12.0 support. Python 3.12 dropped distutils, consequently supporting it required finding a replacement for the setup.py/distutils based build system NumPy was using.
> 
> Is it fine if i use 1.26 for the assignment purpose? Or i should switch to 3.11.9?
> 
> Source: [Numpy release notes](https://numpy.org/devdocs/release/1.26.0-notes.html)

I'm glad you found out the root cause. 

Yes, you can use any version, shouldn't be an issue

**Comment by GamerDra** [comment]
Thank you:)
